-- Retail Sales Analysis - MySQL
CREATE DATABASE retail_sales;
 
USE retail_sales; 
 
-- Create Table
CREATE TABLE retail_table (
    `Transaction ID` INT PRIMARY KEY,
    `Date` DATE,
    `Customer ID` VARCHAR(10),
    Gender VARCHAR(10),
    Age SMALLINT,
    `Product Category` VARCHAR(100),
    Quantity SMALLINT,
    `Price per Unit` DECIMAL(10 , 2 ),
    `Total Amount` DECIMAL(10 , 2 )
);


SELECT *
FROM retail_table; 

-- Imported the retial_sales_csv dataset from desktop
SELECT * FROM retail_table
LIMIT 10;

-- Data cleaning
SELECT COUNT(*)
FROM retail_table;
 
SELECT COUNT(DISTINCT `Transaction ID`)
FROM retail_table; 

SELECT DISTINCT age
FROM retail_table; 
     
-- Checking for null values
SELECT date, quantity, gender
FROM retail_table
WHERE age IS NULL; 

SELECT * FROM retail_table
WHERE  
    `Transaction ID` IS NULL
        OR `Date` IS NULL
        OR `Customer ID` IS NULL
        OR Gender IS NULL
        OR Age IS NULL
        OR `Product Category` IS NULL
        OR Quantity IS NULL
        OR `Price per Unit` IS NULL
        OR `Total Amount` IS NULL;
 
-- Data Exploration
-- How many unique CUSTOMERS do we have? 
SELECT COUNT(DISTINCT `Customer ID`)
FROM retail_table; 

-- How many unique PRODUCT CATEGORIES do we have? 
SELECT DISTINCT `Product Category`
FROM retail_table;


-- BUSINESS QUESTIONS
-- Time-Based Questions
-- Q1.What is the total revenue for December?
SELECT SUM(`Total Amount`) AS `Total revenue`
FROM retail_table
WHERE MONTH(date) = 12; 

-- Q2.What is the monthly total revenue across all months?
SELECT  
    SUM(`Total Amount`) AS `Total revenue`,
    MONTH(`Date`) AS Month,
    YEAR(`Date`) AS Year
FROM retail_table
GROUP BY YEAR(`Date`) , MONTH(`Date`)
ORDER BY `Total revenue` DESC; 

-- Q3.Which month had the highest sales revenue?
SELECT Year, Month, `Total revenue`
FROM
    (SELECT 
        SUM(`Total Amount`) AS `Total revenue`,
            MONTH(`Date`) AS Month,
            YEAR(`Date`) AS Year
    FROM
        retail_table
    GROUP BY YEAR(`Date`) , MONTH(`Date`)) AS monthly_sales
ORDER BY `Total revenue` DESC
LIMIT 1;  

-- Q4.How many transactions occurred in each month?
SELECT 
    COUNT(`Transaction ID`) AS `Transaction Count`,
    MONTH(`Date`) AS Month,
    YEAR(`Date`) AS Year
FROM retail_table
GROUP BY YEAR(`Date`), MONTH(`Date`)
ORDER BY `Transaction Count` DESC;  
 
-- Q5.What is the average revenue per transaction for each month?
SELECT 
    ROUND(SUM(`Total Amount`) / COUNT(`Transaction ID`), 2) AS `Avg Revenue per Transaction`,
    MONTH(`Date`) AS Month,
    YEAR(`Date`) AS Year
FROM retail_table
GROUP BY YEAR(`Date`), MONTH(`Date`)
ORDER BY `Avg Revenue per Transaction` DESC;  


-- Q6.Which month had the highest number of transactions?
SELECT 
    `Number of Transactions`, `Month`, `Year`
FROM
    (SELECT 
        COUNT(`Transaction ID`) AS `Number of Transactions`,
            MONTH(`Date`) AS `Month`,
            YEAR(`Date`) AS `Year`
    FROM
        retail_table
    GROUP BY YEAR(`Date`), MONTH(`Date`)) AS monthly_number_transactions
WHERE
    `Number of Transactions` = (SELECT 
            MAX(`Number of Transactions`)
        FROM
            (SELECT 
                COUNT(`Transaction ID`) AS `Number of Transactions`
            FROM retail_table
            GROUP BY YEAR(`Date`) , MONTH(`Date`)) AS max_transactions)
ORDER BY `Year` , `Month`; 


-- Q7.How does the total revenue in Q4 compare to Q1?
-- quarter_4
WITH quarter_4 AS (
    SELECT SUM(`Total Amount`) AS total_revenue_q4
    FROM retail_table
    WHERE MONTH(`Date`) IN (10, 11, 12)
),
-- quarter_1
quarter_1 AS (
    SELECT SUM(`Total Amount`) AS total_revenue_q1
    FROM retail_table
    WHERE MONTH(`Date`) IN (1, 2, 3)
)
SELECT  
    q4.total_revenue_q4 AS Total_Revenue_Q4,
    q1.total_revenue_q1 AS Total_Revenue_Q1,
    ROUND(q4.total_revenue_q4 / q1.total_revenue_q1 * 100, 2) AS Q4_vs_Q1_Percentage
FROM
    quarter_4 q4, quarter_1 q1;


-- Q8.What is the total quantity of products sold in December?
SELECT SUM(quantity) AS total_quantity
FROM retail_table
WHERE MONTH(`Date`) = 12; 


-- Customer-Based Questions
-- Q9.What is the total revenue generated by each customer?
SELECT `Customer Id` AS customer,
    SUM(`Total Amount`) AS total_revenue
FROM retail_table
GROUP BY customer
ORDER BY total_revenue DESC; 

-- Q10.How many unique customers made purchases in December?
SELECT COUNT(DISTINCT `Customer ID`) AS unique_customer
FROM retail_table
WHERE MONTH(`Date`) = 12;


-- Q11.What is the average total amount spent by customers?
SELECT Round(AVG(`Total Amount`), 2) AS avg_total_amount
FROM retail_table;


-- Q12.Who are the top 10 customers by total revenue?
WITH rank_of_customers AS (
SELECT `Customer Id` AS customer,
	SUM(`Total Amount`) as total_revenue,
   DENSE_RANK() OVER (ORDER BY SUM(`Total Amount`) DESC) AS ranks 
FROM retail_table
GROUP BY customer
ORDER BY total_revenue DESC)
SELECT *
FROM rank_of_customers
WHERE ranks <= 10;


-- Product-Based Questions 
-- Q13.What is the total revenue for each product category?
SELECT 
    SUM(`Total Amount`) AS total_revenue, 
    `Product Category`
FROM retail_table
GROUP BY `Product Category`
ORDER BY total_revenue DESC;


-- Q14.Which product category had the highest number of units sold?
SELECT 
    SUM(`Quantity`) AS total_units_sold, 
    `Product Category`
FROM retail_table
GROUP BY `Product Category`
ORDER BY total_units_sold DESC;


-- Q15.What is the average price per unit for each product category?
SELECT 
    Round(AVG(`Price per Unit`), 2) AS price_per_unit, 
    `Product Category`
FROM retail_table
GROUP BY `Product Category`
ORDER BY price_per_unit DESC;


-- Q16.What is the total quantity sold for each product category in December?
SELECT SUM(Quantity) AS total_quantity, 
	`Product Category`
FROM retail_table
WHERE MONTH(`Date`) = 12
GROUP BY `Product Category`
ORDER BY total_quantity DESC; 


-- Q17.Which product category generated the least revenue?
SELECT MIN(total_revenue) AS min_total_revenue,
	`Product Category`
FROM ( 
	SELECT 
		SUM(`Total Amount`) AS total_revenue, 
		`Product Category`
	FROM retail_table
	GROUP BY `Product Category`
    ) as total_revenue;  


-- Demographic-Based Questions
-- Q18.What is the total revenue for male customers vs. female customers?
SELECT Gender, 
    SUM(`Total Amount`) AS total_revenue
FROM retail_table
GROUP BY Gender
ORDER BY total_revenue DESC;


-- Q19.Which age group contributed the most revenue?
SELECT 
    CASE
        WHEN Age BETWEEN 0 AND 12 THEN 'Children'
        WHEN Age BETWEEN 13 AND 17 THEN 'Teenagers'
        WHEN Age BETWEEN 18 AND 24 THEN 'Young Adults'
        WHEN Age BETWEEN 25 AND 34 THEN 'Adults (Early)'
        WHEN Age BETWEEN 35 AND 44 THEN 'Adults (Mid-life)'
        WHEN Age BETWEEN 45 AND 54 THEN 'Middle-aged Adults'
        WHEN Age BETWEEN 55 AND 64 THEN 'Older Adults'
        ELSE 'Seniors'
    END AS Age_Group,
    SUM(`Total Amount`) AS Total_Revenue
FROM retail_table
GROUP BY Age_Group
ORDER BY Total_Revenue DESC;


-- Q20.What is the average transaction amount for customers aged 30-40?
SELECT ROUND(AVG(`Total Amount`), 2) AS AVG_Revenue
FROM retail_table
WHERE age IN (30 , 40);


-- Q21.What is the total quantity of products purchased by each gender?
SELECT Gender, 
    SUM(`Quantity`) AS total_quantity
FROM retail_table
GROUP BY Gender
ORDER BY total_quantity DESC;


-- Q22.What is the total number of customers in each age group?
SELECT 
    CASE
        WHEN Age BETWEEN 0 AND 12 THEN 'Children'
        WHEN Age BETWEEN 13 AND 17 THEN 'Teenagers'
        WHEN Age BETWEEN 18 AND 24 THEN 'Young Adults'
        WHEN Age BETWEEN 25 AND 34 THEN 'Adults (Early)'
        WHEN Age BETWEEN 35 AND 44 THEN 'Adults (Mid-life)'
        WHEN Age BETWEEN 45 AND 54 THEN 'Middle-aged Adults'
        WHEN Age BETWEEN 55 AND 64 THEN 'Older Adults'
        ELSE 'Seniors'
    END AS Age_Group,
    COUNT(DISTINCT`Customer ID`) AS Number_of_Customers
FROM retail_table
GROUP BY Age_Group
ORDER BY Number_of_Customers DESC;

 
-- Comparative Questions 
-- Q23.How does the total revenue in December compare to November?
WITH total_december AS (
    SELECT SUM(`Total Amount`) AS total_rev_dec
    FROM retail_table
    WHERE MONTH(`Date`) = 12
),
total_november AS (
    SELECT SUM(`Total Amount`) AS total_rev_nov
    FROM retail_table
    WHERE MONTH(`Date`) = 11
)
SELECT 
    total_december.total_rev_dec AS Revenue_December,
    total_november.total_rev_nov AS Revenue_November,
    (total_december.total_rev_dec - total_november.total_rev_nov) AS Revenue_Difference,
    ROUND((total_december.total_rev_dec / total_november.total_rev_nov) * 100, 2) AS Percent_Difference
FROM 
    total_december
CROSS JOIN 
    total_november;


-- Q24.How do sales for Product Category 'Beauty' compare to Product Category 'Clothing'?
WITH beauty_category AS (
    SELECT SUM(`Total Amount`) AS total_beauty
    FROM retail_table
    WHERE `Product Category` = 'Beauty'
),
clothing_category AS (
    SELECT SUM(`Total Amount`) AS total_clothing
    FROM retail_table
    WHERE `Product Category` = 'Clothing'
) 
SELECT 
	beauty_category.total_beauty as beauty_total_revenue,
    clothing_category.total_clothing as clothing_total_revenue,
    (beauty_category.total_beauty- clothing_category.total_clothing) AS Revenue_Difference,
    ROUND((beauty_category.total_beauty / clothing_category.total_clothing) * 100, 2) AS Percent_Difference
FROM 
    beauty_category
CROSS JOIN 
    clothing_category;


-- Q25.How does the average transaction amount differ between male and female customers?
WITH male_transaction AS (
    SELECT ROUND(AVG(`Total Amount`), 2) AS avg_transaction_male
    FROM retail_table
    WHERE Gender = 'Male'
),
female_transaction AS (
    SELECT ROUND(AVG(`Total Amount`), 2) AS avg_transaction_female
    FROM retail_table
    WHERE Gender = 'Female'
)
SELECT 
    male_transaction.avg_transaction_male AS Avg_Transaction_Male,
    female_transaction.avg_transaction_female AS Avg_Transaction_Female,
    (male_transaction.avg_transaction_male - female_transaction.avg_transaction_female) AS Transaction_Difference
FROM 
    male_transaction
CROSS JOIN 
    female_transaction;


-- ----+----+----















